server:
    port: 9001

eureka:
    instance:
        hostname: localhost
    server: #1.关闭注册中心自我保护机制 2.注册中心清理间隔（单位毫秒，默认60*1000）
        enable-self-preservation: false
        eviction-interval-timer-in-ms: 10000
    client:
        registerWithEureka: false
        fetchRegistry: false
        serviceUrl:
            defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
spring:
  application:
    name: eurka-server
